import type { Metadata } from "next";

import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>this will stay no matter what BECAUSE this is written in the UPMOST Layout.tsx in the App Folder</div>
        {children}
      </body>
    </html>
  );
}
